[[services]]
name = "kernel"

[services.build]
builder = "dockerfile"
dockerfilePath = "deploy/Dockerfile"

[services.deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
