#!/usr/bin/env python3
"""
Synthesizer Agent — combines all drafts + reviews into a final report.
"""

import json
import time
import datetime
from pathlib import Path
from base import FleetAgent

REPORTS_DIR = Path(__file__).parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


class Synthesizer(FleetAgent):
    def __init__(self):
        super().__init__("synthesizer", "synthesizer")
        self.current_cycle = 0
        self.working = False

    def on_event(self, evt):
        data = evt if isinstance(evt, dict) else {}
        if isinstance(data.get("data"), dict):
            data = data["data"]

        if data.get("type") == "phase_change" and data.get("phase") == "synthesizing" and not self.working:
            cycle = data.get("cycle", 0)
            if cycle > self.current_cycle:
                self.current_cycle = cycle
                self.do_synthesize()

    def do_synthesize(self):
        self.working = True

        # Read all drafts and reviews from kernel state
        sections = ""
        topic = ""
        for idx in range(3):
            draft = self.fetch(f"cycle{self.current_cycle}:draft:{idx}")
            review = self.fetch(f"cycle{self.current_cycle}:review:{idx}")

            d = draft.get("content", "") if isinstance(draft, dict) else ""
            r = review.get("content", "") if isinstance(review, dict) else ""
            st = draft.get("subtopic", "") if isinstance(draft, dict) else ""

            if idx == 0 and isinstance(draft, dict):
                # Extract main topic from subtopic
                topic = st.split("—")[0].strip() if "—" in st else st

            sections += f"\n## {st}\n{d}\n\nReview: {r}\n"

        self.log(f"Synthesizing {self.current_cycle}...")

        start = time.monotonic()
        resp = self.think(
            f"Combine these reviewed sections into a polished final report:\n{sections}\n\n"
            f"Write an introduction, incorporate reviewer feedback, and add a conclusion. "
            f"Max 400 words. Professional tone."
        )
        elapsed = (time.monotonic() - start) * 1000

        if resp.get("success"):
            final = resp["content"]

            # Store in kernel state
            self.store(f"cycle{self.current_cycle}:final", {
                "content": final,
                "tokens": resp.get("tokens", 0),
                "cost_usd": resp.get("cost_usd", 0),
            })

            # Save as markdown file
            ts = datetime.datetime.now().strftime("%H%M%S")
            safe = topic[:40].lower().replace(" ", "-").replace(":", "")
            path = REPORTS_DIR / f"cycle-{self.current_cycle:03d}-{safe}-{ts}.md"
            with open(path, "w") as f:
                f.write(f"# {topic}\n\n")
                f.write(f"*CLOVE Fleet Report — Cycle {self.current_cycle} — "
                        f"{datetime.datetime.now().isoformat()}*\n\n")
                f.write(final)
                f.write(f"\n\n---\n*Generated by 10-agent fleet through CLOVE kernel*\n")

            self.log(f"Done ({elapsed:.0f}ms) → {path.name}")
            self.emit({"type": "synthesis_done", "cycle": self.current_cycle})
        else:
            self.log(f"FAILED: {resp.get('error', 'unknown')}")

        self.working = False


if __name__ == "__main__":
    Synthesizer().start()
